#!/usr/bin/env python3
"""Stage 1 -> Stage 2 calibration fidelity: for every shaped configuration of a Stage 1 Pareto front, the search-time
(calibration) score vs its Stage 2 full-data score. Writes tables/table_calib_stage1.tex (main-text Table 1).
LongBench calibration subsets are 30%, RULER 10%. AdaKV's Stage 1 archives are not on this server, so only its pick
and regret are reported (the winner it used vs the full-data best). L2Norm is omitted until its Stage 1 sampling is
verified (PAPER_ISSUES 30e)."""
import csv
import glob
import itertools
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
KV = HERE.parents[1]
NAS, RES = KV / "NAS_Assets", KV / "ICLR_Final_Results"


def kendall(a, b):
    c = d = 0
    for i, j in itertools.combinations(range(len(a)), 2):
        s = (a[i] - a[j]) * (b[i] - b[j])
        c += s > 0
        d += s < 0
    return (c - d) / (c + d) if c + d else float("nan")


def shaped(bud):
    return len(set(int(float(x)) for x in re.findall(r"[\d.]+", bud))) > 1


def front(path, cal, full):
    rs = [r for r in csv.DictReader(open(path)) if shaped(r["budgets"])]
    c = [-float(r[cal]) for r in rs]
    f = [float(r[full]) for r in rs]
    pick = max(range(len(rs)), key=lambda i: c[i])
    best = max(range(len(rs)), key=lambda i: f[i])
    return dict(n=len(rs), gap=sum(x - y for x, y in zip(c, f)) / len(rs), tau=kendall(c, f), ok=pick == best, regret=f[best] - f[pick])


def rows():
    out = {}
    for m in ["snapkv", "h2o"]:
        lb = [front(sorted(glob.glob(str(NAS / c / m / "top_configs" / "summary_*.csv")))[-1], "evicted_attn", "avg_score")
              for c in ["SINGLE_DOCUMENT_QA", "MULTI_DOCUMENT_QA", "SUMMARIZATION"]]
        lb.append(front(NAS / "CODE" / m / "top_configs" / "eval_results.csv", "nas_f2", "mean_score"))
        out[("LongBench", m)] = lb
    out[("RULER", "snapkv")] = [front(NAS / "RULER_ALL" / "snapkv" / "top_configs" / "eval_results_all500.csv", "nas_f2", "mean_score")]
    out[("RULER", "h2o")] = [front(NAS / "RULER_ALL" / "h2o" / "top_configs" / "eval_results.csv", "nas_f2", "mean_score")]
    # AdaKV: winner used (anchor, chosen on calibration) vs full-data best of the Stage 2 front
    used = {"SINGLE_DOCUMENT_QA": 464, "MULTI_DOCUMENT_QA": 188, "CODE": 482}
    ada = {}
    for r in csv.DictReader(open(RES / "ADAKV_RESULTS" / "data" / "longbench_step2_pareto_full_eval.csv")):
        if r["type"] != "uniform":
            ada.setdefault(r["category"], {})[round(float(r["avg_budget"]))] = float(r["avg_score"])
    out[("LongBench", "adakv")] = [dict(n=len(v), gap=None, tau=None, ok=max(v, key=v.get) == used[c], regret=max(v.values()) - v[used[c]])
                                   for c, v in ada.items()]
    rr = {round(float(r["avg_budget"])): float(r["mean_score"]) for r in csv.DictReader(open(RES / "ADAKV_RESULTS" / "data" / "ruler_all_results.csv"))
          if r["stage"].startswith("step2") and shaped(r["budgets"])}
    out[("RULER", "adakv")] = [dict(n=len(rr), gap=None, tau=None, ok=max(rr, key=rr.get) == 2536, regret=max(rr.values()) - rr[2536])]
    return out


def fmt(x, signed=True):
    return "--" if x is None else (f"${x:+.2f}$" if signed else f"{x:.2f}")


def table(out):
    name = {"snapkv": "SnapKV", "h2o": "H2O", "adakv": "AdaKV"}
    order = [("LongBench", "h2o"), ("LongBench", "snapkv"), ("RULER", "h2o"), ("RULER", "snapkv"), None, ("LongBench", "adakv"), ("RULER", "adakv")]
    lines = [r"\begin{tabular}{@{} l l r r r r r @{}}", r"  \toprule",
             r"  \textbf{Bench.} & \textbf{Method} & \textbf{Fronts} & \textbf{Gap} & \textbf{$\tau$} & \textbf{Picks} & \textbf{Regret} \\", r"  \midrule"]
    shade = True
    for k in order:
        if k is None:
            lines.append(r"  \midrule"); shade = True; continue
        v = out[k]
        gaps = [x["gap"] for x in v if x["gap"] is not None]
        taus = [x["tau"] for x in v if x["tau"] is not None]
        g = sum(gaps) / len(gaps) if gaps else None
        t = sum(taus) / len(taus) if taus else None
        if shade:
            lines.append(r"  \rowcolor{gray!10}")
        shade = not shade
        lines.append(f"  {k[0]:9s} & {name[k[1]]:6s} & {len(v)} & {fmt(g)} & {fmt(t)} & {sum(x['ok'] for x in v)}/{len(v)} & "
                     f"{fmt(sum(x['regret'] for x in v) / len(v), False)} \\\\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = rows()
    (HERE / "tables").mkdir(exist_ok=True)
    (HERE / "tables" / "table_calib_stage1.tex").write_text("% GENERATED by calib_stage1.py -- edit the script, not this file.\n" + table(out))
    for k, v in out.items():
        print(k, [(x["n"], None if x["gap"] is None else round(x["gap"], 2), None if x["tau"] is None else round(x["tau"], 2), x["ok"], round(x["regret"], 2)) for x in v])
    lb = [x for k, v in out.items() if k[0] == "LongBench" for x in v]
    print("LongBench picks", sum(x["ok"] for x in lb), "/", len(lb))
