#!/usr/bin/env python3
"""TikZ heatmaps of MOSAIC - uniform gains per subtask/dataset x budget (Appendix breakdown figures).
heatmap(name, panels, rows, lim) writes figures/<name>.tex, compiles it with pdflatex and returns nothing.
panels: [(title, [(col_label, dagger)], {(row, col_label): gain})]; rows: [(row_label, group)] in display order."""
import subprocess
from pathlib import Path

FIG = Path(__file__).resolve().parent / "figures"
POS, NEG, WHITE = (0x1F, 0x4E, 0x79), (0xB2, 0x18, 0x2B), (255, 255, 255)  # chartdark gains, red losses
W, H, GAP = 0.50, 0.30, 0.32  # cell width/height and panel gap (cm)


def _rgb(v, lim):
    a = min(abs(v) / lim, 1.0)
    t = POS if v >= 0 else NEG
    return tuple(round(w + (c - w) * a) for w, c in zip(WHITE, t)), a


def _num(v):
    if abs(v) < 0.05:
        return "0.0"
    return ("+" if v > 0 else r"\textminus{}") + f"{abs(v):.1f}"


def heatmap(name, panels, rows, lim, unit="points"):
    out = [r"\documentclass[border=2pt]{standalone}", r"\usepackage[scaled=0.92]{helvet}", r"\renewcommand\familydefault{\sfdefault}",
           r"\usepackage[T1]{fontenc}", r"\usepackage{tikz}", r"\definecolor{ink}{HTML}{2B2B2B}", r"\begin{document}",
           r"\begin{tikzpicture}[x=1cm, y=1cm, font=\sffamily]"]
    # vertical layout: row i occupies [-(i+1)H, -iH], with a small extra gap between groups
    ys, y, prev = [], 0.0, None
    for lab, grp in rows:
        if prev is not None and grp != prev:
            y -= 0.12
        ys.append(y); y -= H; prev = grp
    bottom = y
    x0 = 0.0
    for pi, (title, cols, vals) in enumerate(panels):
        if pi == 0:  # row labels and group labels left of the first panel
            for (lab, grp), yy in zip(rows, ys):
                out.append(rf"\node[anchor=east, font=\tiny, text=ink] at ({x0 - 0.05:.3f},{yy - H / 2:.3f}) {{{lab}}};")
            groups = []
            for (lab, grp), yy in zip(rows, ys):
                if not groups or groups[-1][0] != grp:
                    groups.append([grp, yy, yy - H])
                else:
                    groups[-1][2] = yy - H
            if any(g[0] for g in groups):
                for grp, top, bot in groups:
                    if not grp or grp.startswith("_"):  # unlabelled group (e.g. the mean row)
                        continue
                    out.append(rf"\draw[ink!50, line width=0.4pt] ({x0 - 0.78:.3f},{top - 0.03:.3f}) -- ({x0 - 0.78:.3f},{bot + 0.03:.3f});")
                    out.append(rf"\node[rotate=90, font=\tiny, text=ink] at ({x0 - 0.9:.3f},{(top + bot) / 2:.3f}) {{{grp}}};")
        for ci, (cl, dag) in enumerate(cols):
            xx = x0 + ci * W
            for (lab, grp), yy in zip(rows, ys):
                v = vals.get((lab, cl))
                if v is None:
                    out.append(rf"\fill[black!6] ({xx:.3f},{yy:.3f}) rectangle ({xx + W:.3f},{yy - H:.3f});")
                    out.append(rf"\node[font=\tiny, text=black!40] at ({xx + W / 2:.3f},{yy - H / 2:.3f}) {{--}};")
                    continue
                (r, g, b), a = _rgb(v, lim)
                out.append(rf"\definecolor{{c}}{{RGB}}{{{r},{g},{b}}}\fill[c] ({xx:.3f},{yy:.3f}) rectangle ({xx + W:.3f},{yy - H:.3f});")
                tc = "white" if a > 0.55 else "ink"
                out.append(rf"\node[font=\fontsize{{5}}{{6}}\selectfont, text={tc}] at ({xx + W / 2:.3f},{yy - H / 2:.3f}) {{{_num(v)}}};")
            out.append(rf"\node[anchor=north, font=\tiny, text=ink] at ({xx + W / 2:.3f},{bottom - 0.03:.3f}) {{{cl}{'$^\dagger$' if dag else ''}}};")
        wpan = len(cols) * W
        out.append(rf"\node[anchor=south, font=\scriptsize\bfseries, text=ink] at ({x0 + wpan / 2:.3f},{0.02:.3f}) {{{title}}};")
        out.append(rf"\draw[black!30, line width=0.3pt] ({x0:.3f},0) rectangle ({x0 + wpan:.3f},{bottom:.3f});")
        x0 += wpan + GAP
    # colour bar
    xb, wb, yb = 0.0, 4.0, bottom - 0.62
    n = 40
    for k in range(n):
        v = -lim + 2 * lim * (k + 0.5) / n
        (r, g, b), _ = _rgb(v, lim)
        out.append(rf"\definecolor{{c}}{{RGB}}{{{r},{g},{b}}}\fill[c] ({xb + wb * k / n:.3f},{yb:.3f}) rectangle ({xb + wb * (k + 1) / n + 0.005:.3f},{yb - 0.14:.3f});")
    out.append(rf"\draw[black!30, line width=0.3pt] ({xb:.3f},{yb:.3f}) rectangle ({xb + wb:.3f},{yb - 0.14:.3f});")
    for v, lab in [(-lim, rf"\textminus{{}}{lim:g}"), (0, "0"), (lim, rf"+{lim:g}")]:
        out.append(rf"\node[anchor=north, font=\tiny, text=ink] at ({xb + wb * (v + lim) / (2 * lim):.3f},{yb - 0.16:.3f}) {{{lab}}};")
    out.append(rf"\node[anchor=west, font=\tiny, text=ink] at ({xb + wb + 0.15:.3f},{yb - 0.07:.3f}) {{MOSAIC \textminus{{}} uniform ({unit})}};")
    out += [r"\end{tikzpicture}", r"\end{document}"]
    (FIG / f"{name}.tex").write_text("% GENERATED by heatmap_fig.py (called from make_appendix.py) -- edit the script, not this file.\n" + "\n".join(out) + "\n")
    subprocess.run(["pdflatex", "-interaction=nonstopmode", f"{name}.tex"], cwd=FIG, stdout=subprocess.DEVNULL, check=True)
