#!/usr/bin/env python3
"""Main LongBench results table (uniform vs MOSAIC per method and budget) -> tables/table_main.tex. RULER has its own table (tables/table_ruler_summary.tex).
MOSAIC = the final configuration, the better of Winner and NAS-refined on full data (three_way.load()). Budgets without a
Stage 4 search show the rescaled Stage 3 winner (dagger), from figures/data/stage3_rows.csv (run make_appendix.py first).
Cells searched with the earlier per-layer floor of 16 are starred."""
import csv
from pathlib import Path

import mistral
import three_way as tw

HERE = Path(__file__).resolve().parent
CATS = ["CODE", "MULTI_DOCUMENT_QA", "SINGLE_DOCUMENT_QA", "SUMMARIZATION"]
DISP = {"Code": "CODE", "MultiDoc": "MULTI_DOCUMENT_QA", "SingleDoc": "SINGLE_DOCUMENT_QA", "Summ": "SUMMARIZATION", "RULER": "RULER_ALL"}
METHODS = ["SnapKV", "H2O", "AdaKV", "L2Norm"] + [mistral.NAMES[m] for m in ["SnapKV", "H2O", "AdaKV", "L2Norm"]]
RMETHODS = ["SnapKV", "H2O", "AdaKV", "L2Norm"] + [mistral.NAMES[m] for m in ["SnapKV", "H2O", "AdaKV", "L2Norm"]]
LABEL = {v: rf"\shortstack[l]{{{k}\\(Mistral)}}" for k, v in mistral.NAMES.items()}
BUDGETS = [128, 256, 512, 1024]


def load():
    out = {}  # (method, CAT, B) -> (uniform, mosaic, floor, rescale_only)
    for (m, bench, cat, b), v in tw.load().items():
        out[(m, cat, b)] = (v["uniform"], max(v.get("winner", -1e9), v.get("bo", -1e9)), v["floor"], False)
    for (m, cat, b), v in mistral.load().items():
        out[(m, cat, b)] = (v["uniform"], max(v.get("winner", -1e9), v["bo"]), v["floor"], False)
    for r in csv.DictReader(open(HERE / "figures" / "data" / "stage3_rows.csv")):
        k = (r["method"], DISP[r["category"]], int(r["budget"]))
        if k not in out:
            out[k] = (float(r["uniform"]), float(r["winner"]), int(r["floor"]), True)
    return out


def cell(v):
    if v is None:
        return "-- & --"
    u, m, floor, resc = v
    mark = ("$^\\dagger$" if resc else "") + ("$^*$" if floor == 16 else "")
    us, ms = f"{u:.2f}", f"{m:.2f}"
    if m > u:
        ms = rf"\textbf{{{ms}}}"
    elif u > m:
        us = rf"\textbf{{{us}}}"
    return f"{us} & {ms}{mark}"


def table(out):
    head = " & ".join(rf"\multicolumn{{2}}{{c}}{{\textbf{{{n}}}}}" for n in ["Code", "Multi-Doc QA", "Single-Doc QA", "Summarization"])
    cmid = " ".join(rf"\cmidrule(lr){{{3 + 2 * i}-{4 + 2 * i}}}" for i in range(4))
    lines = [r"\begin{tabular}{@{} l r rr rr rr rr @{}}", r"  \toprule",
             rf"  & & {head} \\", f"  {cmid}",
             r"  \textbf{Method} & \textbf{B} & " + " & ".join(["Uniform", "MOSAIC"] * 4) + r" \\"]
    for mi, m in enumerate(METHODS):
        lines.append(r"  \midrule")
        rows = [b for b in BUDGETS if any((m, c, b) in out for c in CATS)]
        n = len(rows)
        for i, b in enumerate(rows):
            lead = rf"\multirow{{{n}}}{{*}}{{{LABEL.get(m, m)}}}" if i == 0 else ""
            lines.append(f"  {lead} & {b} & " + " & ".join(cell(out.get((m, c, b))) for c in CATS) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


RBUDGETS = [64, 128, 256, 512, 1024, 1536, 2048]


def ruler_table(out):
    """RULER, compact: one column per budget, two rows (U, M) per method."""
    lines = [r"\begin{tabular}{@{} l l " + "r" * len(RBUDGETS) + r" @{}}", r"  \toprule",
             r"  \textbf{Method} & & " + " & ".join(rf"\textbf{{{b}}}" for b in RBUDGETS) + r" \\"]
    for m in RMETHODS:
        lines.append(r"  \midrule")
        us, ms = [], []
        for b in RBUDGETS:
            v = out.get((m, "RULER_ALL", b))
            if v is None:
                us.append("--"); ms.append("--"); continue
            u, x, floor, resc = v
            mark = "$^\\dagger$" if resc else ""
            a, c = f"{u:.2f}", f"{x:.2f}"
            if x > u:
                c = rf"\textbf{{{c}}}"
            elif u > x:
                a = rf"\textbf{{{a}}}"
            us.append(a); ms.append(c + mark)
        lines.append(rf"  \multirow{{2}}{{*}}{{{LABEL.get(m, m)}}} & Uniform & " + " & ".join(us) + r" \\")
        lines.append(f"   & MOSAIC & " + " & ".join(ms) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = load()
    (HERE / "tables" / "table_ruler_main.tex").write_text("% GENERATED by make_main_table.py -- edit the script, not this file.\n" + ruler_table(out))
    (HERE / "tables").mkdir(exist_ok=True)
    (HERE / "tables" / "table_main.tex").write_text("% GENERATED by make_main_table.py -- edit the script, not this file.\n" + table(out))
    shown = {k: v for k, v in out.items() if k[2] in BUDGETS}
    print(f"cells shown {len(shown)} (rescale-only {sum(v[3] for v in shown.values())}, floor 16 {sum(v[2] == 16 for v in shown.values())}); "
          f"MOSAIC > uniform {sum(v[1] > v[0] for v in shown.values())}")
