#!/usr/bin/env python3
"""Print the README's two result tables (the layout of the paper's Tables 2 and 3) from results/cells.csv.
    python scripts/make_readme_tables.py            # prints Markdown
    python scripts/make_readme_tables.py --write    # rewrites the block between the RESULTS markers in README.md"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
rows = list(csv.DictReader(open(ROOT / "results" / "cells.csv")))
cell = {(r["model"], r["method"], r["task"], int(r["budget"])): r for r in rows}
MODELS = [("Llama-3-8B-Instruct", "Llama-3-8B"), ("Mistral-7B-Instruct-v0.2", "Mistral-7B")]
METHODS = ["SnapKV", "H2O", "AdaKV", "L2Norm"]


def pair(r):
    """'uniform / MOSAIC' with the better one in bold; '--' when the cell was not run."""
    if r is None:
        return "--"
    u = f"{float(r['uniform']):.2f}"
    if not r["mosaic"]:
        return f"{u} / --"
    m = f"{float(r['mosaic']):.2f}"
    return f"**{u}** / {m}" if float(u) > float(m) else f"{u} / **{m}**" if float(m) > float(u) else f"{u} / {m}"


def longbench():
    tasks = ["Code", "Multi-Doc QA", "Single-Doc QA", "Summarization"]
    out = ["| Model | Method | Budget | " + " | ".join(tasks) + " |", "|---|---|---:|" + "---:|" * len(tasks)]
    for mk, ml in MODELS:
        for me in METHODS:
            for b in (128, 256, 512, 1024):
                rs = [cell.get((mk, me, t, b)) for t in tasks]
                if any(rs):
                    out.append(f"| {ml} | {me} | {b} | " + " | ".join(pair(r) for r in rs) + " |")
    return "\n".join(out)


def ruler():
    buds = (64, 128, 256, 512, 1024, 1536, 2048)
    out = ["| Model | Method | " + " | ".join(f"B{b}" for b in buds) + " |", "|---|---|" + "---:|" * len(buds)]
    for mk, ml in MODELS:
        for me in METHODS:
            out.append(f"| {ml} | {me} | " + " | ".join(pair(cell.get((mk, me, "RULER", b))) for b in buds) + " |")
    return "\n".join(out)


block = f"""<!-- RESULTS:START (generated by scripts/make_readme_tables.py) -->
**LongBench** (full data; category mean over its datasets). Each cell is uniform allocation / MOSAIC at the same average
per-layer budget `B`; the better of the two is in bold. `--`: not evaluated. Mistral SnapKV, H2O and AdaKV have only
a Stage 1 search on Summarization, so only their uniform score is given.

{longbench()}

**RULER** (full data; string-match accuracy averaged over 11 subtasks). Same format as above.

{ruler()}
<!-- RESULTS:END -->"""
if "--write" in sys.argv:
    p = ROOT / "README.md"
    s = p.read_text()
    a, b = s.index("<!-- RESULTS:START"), s.index("<!-- RESULTS:END -->") + len("<!-- RESULTS:END -->")
    p.write_text(s[:a] + block + s[b:])
else:
    print(block)
